# Generated by Django 4.2.7 on 2023-12-05 10:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(null=True)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('url', models.URLField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.categorymodel')),
            ],
        ),
    ]
