# Generated by Django 4.2.7 on 2023-12-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_quantity_alter_productmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='url',
        ),
    ]
