# Generated by Django 4.2.7 on 2023-12-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productmodel_file_remove_productmodel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='img',
            new_name='image',
        ),
    ]
